### ISSUE TITLE
 Error: Cannot find module 'eslint-config-xo'

### ISSUE THREAD

**Issue by saurav1005** [sindresorhus/eslint-config-xo-space#5]
Installation version details
node - 6.3.1
npm - 3.10.3
eslint global-  3.9.1
eslint local - 3.9.1
eslint-config-xo-space - 0.12.0

While running gulp serve getting the below error.  

> [10:45:34] Error: Cannot find module 'eslint-config-xo'
Referenced from: xo-space
Referenced from: D:\Learning\Angular\Angular1.5\package.json 
at Object.ModuleResolver.resolve (D:\Learning\Angular\Angular1.5\node_modules\gulp-eslint\node_modules\eslint\lib\util\module-resolver.js:75:19)
at resolve (D:\Learning\Angular\Angular1.5\node_modules\gulp-eslint\node_modules\eslint\lib\config\config-file.js:479:33)
at load (D:\Learning\Angular\Angular1.5\node_modules\gulp-eslint\node_modules\eslint\lib\config\config-file.js:496:24)
at D:\Learning\Angular\Angular1.5\node_modules\gulp-eslint\node_modules\esli
nt\lib\config\config-file.js:392:36
at Array.reduceRight (native)
at applyExtends (D:\Learning\Angular\Angular1.5\node_modules\gulp-eslint\nod
e_modules\eslint\lib\config\config-file.js:363:28)
at load (D:\Learning\Angular\Angular1.5\node_modules\gulp-eslint\node_module
s\eslint\lib\config\config-file.js:530:22)
at D:\Learning\Angular\Angular1.5\node_modules\gulp-eslint\node_modules\esli
nt\lib\config\config-file.js:392:36
 at Array.reduceRight (native)
at applyExtends (D:\Learning\Angular\Angular1.5\node_modules\gulp-eslint\nod
e_modules\eslint\lib\config\config-file.js:363:28)
    at Object.load (D:\Learning\Angular\Angular1.5\node_modules\gulp-eslint\node
_modules\eslint\lib\config\config-file.js:530:22)
    at loadConfig (D:\Learning\Angular\Angular1.5\node_modules\gulp-eslint\node_
modules\eslint\lib\config.js:64:33)
    at getLocalConfig (D:\Learning\Angular\Angular1.5\node_modules\gulp-eslint\n
ode_modules\eslint\lib\config.js:126:23)
    at Config.getConfig (D:\Learning\Angular\Angular1.5\node_modules\gulp-eslint
\node_modules\eslint\lib\config.js:227:22)
    at processText (D:\Learning\Angular\Angular1.5\node_modules\gulp-eslint\node
_modules\eslint\lib\cli-engine.js:223:27)
    at CLIEngine.executeOnText (D:\Learning\Angular\Angular1.5\node_modules\gulp
-eslint\node_modules\eslint\lib\cli-engine.js:761:26)

If I run npm install for eslint-config-xo module (v0.17.0) then the below issue comes up 
 Error: xo:
        Configuration for rule "valid-typeof" is invalid:
        Value "[object Object]" has more items than allowed.

**Comment by sindresorhus** [comment]
> Configuration for rule "valid-typeof" is invalid:
Value "[object Object]" has more items than allowed.

This is usually a sign of not having the required ESLint version.

**Comment by saurav1005** [comment]
These are the versions used 
node - 6.3.1
npm - 3.10.3
eslint global- 3.9.1
eslint local - 3.9.1
eslint-config-xo-space - 0.12.0
eslint-config-xo - 0.17.0 

The failure happens on running gulp serve task.

**Comment by shinnn** [comment]
@saurav1005 

1. Please show us the output of `npm ls eslint`.
2. Can you remove `node_modules` directory, reinstall all dependencies and try running  the gulp task again? I guess the cause of this problem is half-done dependency deduplication.

**Comment by saurav1005** [comment]
@shinnn 

Below is the output for point 1. 
D:\Learning\Angular\Angular1.5>npm ls eslint
D:\Learning\Angular\Angular1.5
+-- eslint@3.9.1
+-- gulp-eslint@2.1.0
| `-- eslint@2.13.1
`-- UNMET PEER DEPENDENCY jasmine-core@*

npm ERR! peer dep missing: jasmine-core@*, required by karma-jasmine@1.0.2

**Comment by shinnn** [comment]
So my assumption was right.

Upgrade gulp-eslint to v3.x. gulp-eslint v2.x doesn't support rule options introduced in ESLint >= v3.0.0.
